kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/ceanders/undertow-servlet-s2i'
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '104366'
  name: undertow-servlet-s-2-i
  labels:
    app: undertow-servlet-s-2-i
    app.kubernetes.io/component: undertow-servlet-s-2-i
    app.kubernetes.io/instance: undertow-servlet-s-2-i
    app.kubernetes.io/name: undertow-servlet-s-2-i
    app.kubernetes.io/part-of: undertow-servlet-s-2-i-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'undertow-servlet-s-2-i:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/ceanders/undertow-servlet-s2i'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: undertow-servlet-s-2-i-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: undertow-servlet-s-2-i-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/java@sha256:0618d4d6ebc7f40df445063c167d101d12e4955bc60b15713af43bd188104ab5
    - type: ConfigChange
  runPolicy: Serial