kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/ceanders/undertow-servlet-s2i'
    openshift.io/generated-by: OpenShiftWebConsole
  name: undertow-servlet-s-2-i
  labels:
    app: undertow-servlet-s-2-i
    app.kubernetes.io/component: undertow-servlet-s-2-i
    app.kubernetes.io/instance: undertow-servlet-s-2-i
    app.kubernetes.io/name: undertow-servlet-s-2-i
    app.kubernetes.io/part-of: undertow-servlet-s-2-i-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  lookupPolicy:
    local: false
