kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: undertow-app-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: undertow-servlet-s-2-i
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30