kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: undertow-app-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: undertow-servlet-s-2-i
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50