apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      volumeClaimTemplate:
        spec:
          storageClassName: ovirt-csi-ssd
          resources:
            requests:
              storage: 40Gi
      retention: 72h
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: ovirt-csi-ssd
          resources:
            requests:
              storage: 10Gi