apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: undertow-app-triggertemplate
spec:
  params:
    - description: The git repository url
      name: git-repo-url
    - default: master
      description: The git revision
      name: git-revision
    - description: The name of the deployment to be created / patched
      name: git-repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: undertow-app-build-and-deploy-
      spec:
        pipelineRef:
          name: undertow-app-build-and-deploy
        serviceAccountName: pipeline
        workspaces:
          - name: scratchpad
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
